language: ruby
cache: bundler
rvm:
  - 2.3.8
  - 2.4.5
  - 2.5.3

env:
  - "RAILS_VERSION=4.2.11"
  - "RAILS_VERSION=5.0.7"
  - "RAILS_VERSION=5.1.6"
  - "RAILS_VERSION=5.2.0"
  - "RAILS_VERSION=5.2.1"
  - "RAILS_VERSION=5.2.2"
