language: ruby
rvm:
  - 2.0.0
  - 2.1
  - 2.2

env:
  - "RAILS_VERSION=3.2.21"
  - "RAILS_VERSION=4.0.13"
  - "RAILS_VERSION=4.1.10"
  - "RAILS_VERSION=4.2.1"

matrix:
  exclude:
    - env: "RAILS_VERSION=3.2.21"
      rvm: 2.2
