language: ruby
cache: bundler
rvm:
  - 2.2.9
  - 2.3.6
  - 2.4.3
  - 2.5.0

env:
  - "RAILS_VERSION=4.2.0"
  - "RAILS_VERSION=5.0.0"
  - "RAILS_VERSION=5.1.0"
  - "RAILS_VERSION=5.2.0"
  - "RAILS_VERSION=5.2.1"
